language: android

jdk:
  - oraclejdk8

android:
  components:
    # Update Android SDK tools
    - tools
    - platform-tools
    # Install required tools and Android API
    - build-tools-25.0.2
    - android-25
    # Support library
    - extra-android-m2repository

notifications:
  email: false
